apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-generator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: data-generator
    spec:
      containers:
      - image: cricketeerone/kelda-starter-flask-kafka:0.0.1
        name: data-generator
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: kelda-demo-cp-kafka:9092
