apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-zookeeper.fullname" . }}
  labels:
    app: {{ template "cp-zookeeper.name" . }}
    chart: {{ template "cp-zookeeper.chart" . }}
    release: {{ .Values.helmReleaseName }}
    heritage: {{ .Values.helmReleaseService }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.clientPort }}
      name: client
  selector:
    app: {{ template "cp-zookeeper.name" . }}
    release: {{ .Values.helmReleaseName }}
