apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-kafka.fullname" . }}-headless
  labels:
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Values.helmReleaseName }}
    heritage: {{ .Values.helmServiceName }}
spec:
  ports:
    - port: 9092
      name: broker
  clusterIP: None
  selector:
    app: {{ template "cp-kafka.name" . }}
    release: {{ .Values.helmReleaseName }}
